### ISSUE TITLE
filter do not work on list which generated by the "for" form

### ISSUE THREAD

**Issue by lhrkkk** [halgari/clojure-py#174]
just open a clojurepy repl and enter this 

```
user=> (filter #(> % 4) (for [ i (range 10) ] i))
(Traceback (most recent call last):
  File "/Users/lhr/.virtualenvs/new/bin/clojurepy", line 11, in <module>
    sys.exit(main())
  File "/Users/lhr/.virtualenvs/new/lib/python2.7/site-packages/clojure/main.py", line 91, in main
    clojure.repl.run_repl(comp)
  File "/Users/lhr/.virtualenvs/new/lib/python2.7/site-packages/clojure/repl.py", line 123, in run_repl
    RT.printTo(out)
  File "/Users/lhr/.virtualenvs/new/lib/python2.7/site-packages/clojure/lang/rt.py", line 328, in printTo
    protocols.writeAsReplString(obj, writer)
  File "/Users/lhr/.virtualenvs/new/lib/python2.7/site-packages/clojure/lang/protocol.py", line 46, in __call__
    return getattr(x, self.attrname)(*args)
  File "/Users/lhr/.virtualenvs/new/lib/python2.7/site-packages/clojure/core.clj", line 796, in clojure.core/LazySeq_writeAsReplString
    (loop [s (.seq self)]
  File "/Users/lhr/.virtualenvs/new/lib/python2.7/site-packages/clojure/core.clj", line 0, in clojure.core/LazySeq_seq
    (l
  File "/Users/lhr/.virtualenvs/new/lib/python2.7/site-packages/clojure/core.clj", line 0, in clojure.core/LazySeq_sval
    (l
  File "/Users/lhr/.virtualenvs/new/lib/python2.7/site-packages/clojure/core.clj", line 1812, in clojure.core/filter304_auto_
    (when (pred (.nth c i))
AttributeError: 'ArrayChunk' object has no attribute 'nth'
```

but this code deed run in a clojure repl without any error.

**Comment by aisk** [comment]
@lhrkkk I think this repo is dead.
